// Command openapi-ts turns the goa-generated OpenAPI 3 spec into a single
// TypeScript declaration file of the component schemas, so the frontend stops
// hand-maintaining ~40 interfaces that drift from the API every time a payload
// changes.
//
// It is intentionally small: goa's output is regular (object/properties/
// required, $ref, arrays, string enums, additionalProperties maps), so a full
// OpenAPI type system is not needed. Anything it does not recognise degrades to
// `unknown` rather than guessing.
//
//	go run ./tools/openapi-ts \
//	  -in api/gen/http/openapi3.json \
//	  -out frontend/src/api/schema.gen.ts
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

func main() {
	in := flag.String("in", "api/gen/http/openapi3.json", "path to the OpenAPI 3 JSON spec")
	out := flag.String("out", "frontend/src/api/schema.gen.ts", "path to write the .ts declarations")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		fail("read %s: %v", *in, err)
	}
	var doc struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		fail("parse %s: %v", *in, err)
	}
	if len(doc.Components.Schemas) == 0 {
		fail("no components.schemas in %s", *in)
	}

	names := make([]string, 0, len(doc.Components.Schemas))
	for n := range doc.Components.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by tools/openapi-ts from api/gen/http/openapi3.json. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: make generate-api-types\n\n")

	for _, name := range names {
		var node map[string]any
		if err := json.Unmarshal(doc.Components.Schemas[name], &node); err != nil {
			fail("parse schema %s: %v", name, err)
		}
		writeNamed(&b, name, node)
	}

	// #nosec G306 -- generated TypeScript source; world-readable is intended.
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Printf("openapi-ts: %d schemas -> %s\n", len(names), *out)
}

// writeNamed emits a top-level declaration for one component schema: an
// `interface` when it is a plain object with properties, otherwise a `type`
// alias.
func writeNamed(b *strings.Builder, name string, node map[string]any) {
	if props, ok := node["properties"].(map[string]any); ok && node["additionalProperties"] == nil {
		fmt.Fprintf(b, "export interface %s ", name)
		writeObject(b, props, requiredSet(node), 0)
		b.WriteString("\n\n")
		return
	}
	fmt.Fprintf(b, "export type %s = %s;\n\n", name, tsType(node, 0))
}

func writeObject(b *strings.Builder, props map[string]any, required map[string]bool, depth int) {
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		b.WriteString("{}")
		return
	}
	indent := strings.Repeat("  ", depth+1)
	b.WriteString("{\n")
	for _, k := range keys {
		field, _ := props[k].(map[string]any)
		opt := ""
		if !required[k] {
			opt = "?"
		}
		fmt.Fprintf(b, "%s%s%s: %s;\n", indent, tsKey(k), opt, tsType(field, depth+1))
	}
	fmt.Fprintf(b, "%s}", strings.Repeat("  ", depth))
}

// tsType maps one schema node to a TypeScript type expression.
func tsType(node map[string]any, depth int) string {
	if node == nil {
		return "unknown"
	}
	if ref, ok := node["$ref"].(string); ok {
		return refName(ref)
	}
	if parts, ok := node["allOf"].([]any); ok {
		return joinComposite(parts, " & ", depth)
	}
	if parts, ok := node["oneOf"].([]any); ok {
		return joinComposite(parts, " | ", depth)
	}
	if parts, ok := node["anyOf"].([]any); ok {
		return joinComposite(parts, " | ", depth)
	}

	switch typeStr(node["type"]) {
	case "string":
		if enum, ok := node["enum"].([]any); ok && len(enum) > 0 {
			lits := make([]string, 0, len(enum))
			for _, e := range enum {
				if s, ok := e.(string); ok {
					lits = append(lits, fmt.Sprintf("%q", s))
				}
			}
			if len(lits) > 0 {
				return strings.Join(lits, " | ")
			}
		}
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		items, _ := node["items"].(map[string]any)
		elem := tsType(items, depth)
		if strings.ContainsAny(elem, "|&") {
			elem = "(" + elem + ")"
		}
		return elem + "[]"
	case "object":
		if ap, ok := node["additionalProperties"]; ok {
			var val string
			switch v := ap.(type) {
			case bool:
				val = "unknown"
			case map[string]any:
				val = tsType(v, depth)
			default:
				val = "unknown"
			}
			return "{ [key: string]: " + val + " }"
		}
		if props, ok := node["properties"].(map[string]any); ok {
			var sb strings.Builder
			writeObject(&sb, props, requiredSet(node), depth)
			return sb.String()
		}
		return "Record<string, unknown>"
	}

	// No usable "type": a bare {} (goa uses this for free-form JSON) or an
	// unrecognised shape.
	if _, ok := node["properties"]; ok {
		var sb strings.Builder
		writeObject(&sb, node["properties"].(map[string]any), requiredSet(node), depth)
		return sb.String()
	}
	return "unknown"
}

func joinComposite(parts []any, sep string, depth int) string {
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		m, _ := p.(map[string]any)
		t := tsType(m, depth)
		if strings.Contains(t, " ") && !strings.HasPrefix(t, "{") {
			t = "(" + t + ")"
		}
		out = append(out, t)
	}
	if len(out) == 0 {
		return "unknown"
	}
	return strings.Join(out, sep)
}

func requiredSet(node map[string]any) map[string]bool {
	set := map[string]bool{}
	if req, ok := node["required"].([]any); ok {
		for _, r := range req {
			if s, ok := r.(string); ok {
				set[s] = true
			}
		}
	}
	return set
}

func typeStr(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case []any:
		// e.g. ["string","null"] — take the first non-null.
		for _, e := range t {
			if s, ok := e.(string); ok && s != "null" {
				return s
			}
		}
	}
	return ""
}

func refName(ref string) string {
	i := strings.LastIndex(ref, "/")
	if i < 0 {
		return "unknown"
	}
	return ref[i+1:]
}

var identRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func tsKey(k string) string {
	if identRe.MatchString(k) {
		return k
	}
	return fmt.Sprintf("%q", k)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "openapi-ts: "+format+"\n", args...)
	os.Exit(1)
}
